# Generated by Django 5.1.7 on 2025-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
