# Generated by Django 5.1.7 on 2025-03-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_availability_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='slug',
        ),
    ]
