# Generated by Django 5.1.7 on 2025-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_availability_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('referral', 'Referral')], max_length=20),
        ),
    ]
